// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as StoreImport } from './routes/_store'
import { Route as MeImport } from './routes/_me'
import { Route as Import } from './routes/*'
import { Route as IndexImport } from './routes/index'
import { Route as StoreStoreStoreIdImport } from './routes/_store.store.$storeId'
import { Route as MeMeHomeImport } from './routes/_me.me.home'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const StoreRoute = StoreImport.update({
  id: '/_store',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/_me',
  getParentRoute: () => rootRoute,
} as any)

const Route = Import.update({
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoreStoreStoreIdRoute = StoreStoreStoreIdImport.update({
  path: '/store/$storeId',
  getParentRoute: () => StoreRoute,
} as any)

const MeMeHomeRoute = MeMeHomeImport.update({
  path: '/me/home',
  getParentRoute: () => MeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/*': {
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_me': {
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/_store': {
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_me/me/home': {
      preLoaderRoute: typeof MeMeHomeImport
      parentRoute: typeof MeImport
    }
    '/_store/store/$storeId': {
      preLoaderRoute: typeof StoreStoreStoreIdImport
      parentRoute: typeof StoreImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  Route,
  MeRoute.addChildren([MeMeHomeRoute]),
  StoreRoute.addChildren([StoreStoreStoreIdRoute]),
  SigninRoute,
  SignupRoute,
])
