name: Deployments

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deployments-workflow:
    uses: imenesesl/heroku-workflow/.github/workflows/deployments-workflow.yml@main
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    with:
      prod_app_name: react-vite
      stg_app_name: stg-react-vite
      heroku_email: "luismenesesep@gmail.com"
